language: php

php:
    - 5.5

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover-coverage.xml